X00TD: doze: Define used libraries
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (out/target/common/obj/APPS/Doze_intermediates/manifest/AndroidManifest.xml):
		<uses-library android:name="androidx.window.extensions" android:required="false"/>
		<uses-library android:name="androidx.window.sidecar" android:required="false"/>

Change-Id: I286cb1912e6cf053410cc4044de4ddd2b88776b6